# GitLab CI/CD Pipeline for Code Review Quality Assurance

stages:
  - validate
  - test
  - quality
  - security
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_VERSION: "3.12"

cache:
  paths:
    - .cache/pip
    - venv/

# ä»£ç æ ¼å¼æ£€æŸ¥
code_format:
  stage: validate
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install black isort flake8
  script:
    - black --check --diff .
    - isort --check-only --diff .
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ç±»åž‹æ£€æŸ¥
type_check:
  stage: validate
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install mypy types-requests
    - pip install -r requirements.txt
  script:
    - mypy server.py --ignore-missing-imports
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# å•å…ƒæµ‹è¯•
unit_tests:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - python -m pytest tests/ -v --cov=. --cov-report=xml --cov-report=term
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ä»£ç è´¨é‡åˆ†æž
code_quality:
  stage: quality
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install pylint radon xenon
    - pip install -r requirements.txt
  script:
    - pylint server.py --output-format=text --reports=yes --exit-zero > pylint-report.txt
    - radon cc server.py --show-complexity --average
    - radon mi server.py --show
    - xenon --max-absolute B --max-modules A --max-average A server.py
  artifacts:
    paths:
      - pylint-report.txt
    expire_in: 1 week
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# å®‰å…¨æ‰«æ
security_scan:
  stage: security
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install bandit safety
    - pip install -r requirements.txt
  script:
    - bandit -r . -f json -o bandit-report.json || true
    - safety check --json --output safety-report.json || true
    - echo "Security scan completed"
  artifacts:
    paths:
      - bandit-report.json
      - safety-report.json
    expire_in: 1 week
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ä¾èµ–æ‰«æ
dependency_scan:
  stage: security
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install pip-audit
  script:
    - pip-audit --output=json --output-file=dependency-audit.json || true
  artifacts:
    paths:
      - dependency-audit.json
    expire_in: 1 week
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# MCPæœåŠ¡å™¨åŠŸèƒ½æµ‹è¯•
mcp_server_test:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    # åˆ›å»ºæµ‹è¯•ç”¨çš„çŽ¯å¢ƒå˜é‡
    - echo "GITLAB_TOKEN=test_token" > .env
    - echo "GITLAB_HOST=gitlab.example.com" >> .env
  script:
    - python -c "import server; print('Server imports successfully')"
    - python -m pytest tests/test_server.py -v
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# æ–‡æ¡£æ£€æŸ¥
docs_check:
  stage: validate
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install pydocstyle
  script:
    - pydocstyle server.py --convention=google
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# æ€§èƒ½æµ‹è¯•
performance_test:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install memory-profiler psutil
  script:
    - python -c "
      import cProfile
      import pstats
      import server
      pr = cProfile.Profile()
      pr.enable()
      # è¿™é‡Œæ·»åŠ æ€§èƒ½æµ‹è¯•ä»£ç 
      pr.disable()
      stats = pstats.Stats(pr)
      stats.sort_stats('cumulative')
      stats.print_stats(10)
      "
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# ä»£ç å®¡æŸ¥æé†’
review_reminder:
  stage: quality
  image: alpine:latest
  before_script:
    - apk add --no-cache curl jq
  script:
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        echo "ðŸ” ä»£ç å®¡æŸ¥æé†’ï¼š"
        echo "âœ… è¯·ç¡®ä¿ä»£ç ç¬¦åˆé¡¹ç›®è§„èŒƒ"
        echo "âœ… è¯·æ£€æŸ¥å®‰å…¨æ€§å’Œæ€§èƒ½"
        echo "âœ… è¯·éªŒè¯æµ‹è¯•è¦†ç›–çŽ‡"
        echo "âœ… è¯·ç¡®ä¿æ–‡æ¡£æ›´æ–°"
        echo "ðŸ“‹ å‚è€ƒ: CODE_REVIEW_GUIDELINES.md"
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# éƒ¨ç½²åˆ°å¼€å‘çŽ¯å¢ƒ
deploy_dev:
  stage: deploy
  image: alpine:latest
  script:
    - echo "éƒ¨ç½²åˆ°å¼€å‘çŽ¯å¢ƒ"
    - echo "éªŒè¯MCPæœåŠ¡å™¨é…ç½®"
    - echo "æ£€æŸ¥çŽ¯å¢ƒå˜é‡è®¾ç½®"
  environment:
    name: development
    url: https://dev.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  when: manual

# éƒ¨ç½²åˆ°ç”Ÿäº§çŽ¯å¢ƒ
deploy_prod:
  stage: deploy
  image: alpine:latest
  script:
    - echo "éƒ¨ç½²åˆ°ç”Ÿäº§çŽ¯å¢ƒ"
    - echo "éªŒè¯ç”Ÿäº§çŽ¯å¢ƒé…ç½®"
    - echo "æ‰§è¡Œå¥åº·æ£€æŸ¥"
  environment:
    name: production
    url: https://prod.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  when: manual
  only:
    - main
    - master

# ä»£ç è¦†ç›–çŽ‡æ£€æŸ¥
coverage_check:
  stage: quality
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - python -m pytest tests/ --cov=. --cov-report=term --cov-fail-under=70
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true

# ç”Ÿæˆä»£ç è´¨é‡æŠ¥å‘Š
quality_report:
  stage: quality
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - |
      echo "ðŸ“Š ä»£ç è´¨é‡æŠ¥å‘Š" > quality-report.md
      echo "==================" >> quality-report.md
      echo "" >> quality-report.md
      echo "## æ£€æŸ¥é¡¹ç›®:" >> quality-report.md
      echo "- âœ… ä»£ç æ ¼å¼æ£€æŸ¥" >> quality-report.md
      echo "- âœ… ç±»åž‹æ£€æŸ¥" >> quality-report.md
      echo "- âœ… å•å…ƒæµ‹è¯•" >> quality-report.md
      echo "- âœ… ä»£ç è´¨é‡åˆ†æž" >> quality-report.md
      echo "- âœ… å®‰å…¨æ‰«æ" >> quality-report.md
      echo "- âœ… ä¾èµ–æ£€æŸ¥" >> quality-report.md
      echo "" >> quality-report.md
      echo "è¯¦ç»†æŠ¥å‘Šè¯·æŸ¥çœ‹å„ä¸ªé˜¶æ®µçš„è¾“å‡ºã€‚" >> quality-report.md
  artifacts:
    paths:
      - quality-report.md
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
